### PR TITLE
Docutils dependency now included in setup.py

### LINKED ISSUE #16: docutils.core module not available in Ubuntu 14 by default
Program gives import error on Ubuntu 14 due to https://github.com/mantidproject/fitbenchmarking/blob/29eaecbf601dd392dc82d2d8844f871ebb5ba78e/fitbenchmarking/results_output.py#L27
as python docutils.core is not available by default on this platform.

To solve this externally user needs to type in terminal:
`sudo apt-get install python-docutils`

A workaround without requiring the user to do anything is preferred.

### PR DESCRIPTION
**Pull request by bb511**
This comes after PR #21 
This fixes #16
 
Just included install_packages=["python-docutils"] in setup.py. When users will run setup, docutils will also be installed on their machine.

To test:
1. On Ubuntu 16 make sure the package docutils is not installed
    - check /usr/lib/python2.7, if you find any folder with docutils in its name run `sudo apt remove python-docutils` in the terminal
    - check /usr/local/lib/python2.7, if you find any folder with docutils in its name run `sudo rm -r /usr/local/lib/python2.7/NameOfFolderWithDocutils`
2. Run example_runScript.py in mantidpython
    - to do this open a terminal and run `cd /opt/Mantid/bin` or wherever mantidplot is installed on your machine
    - once in the bin directory, run `./mantidpython` in terminal
    - here cd to the fitbenchmarking folder and run example_runScript.py
    - this should return an **ImportError**
3. In a normal terminal run `sudo python setup.py develop` (in the /fitbenchmarking dir)
    - make sure you have the setuptools package installed (this won't be needed by the future user)
    - to install setuptools run `sudo apt-get install python-setuptools` in the terminal
4. Close the mantidpython terminal and open it again
5. Run example_runScript.py in the new mantidpython terminal

Issue should now be fixed.

### CODE REVIEW

**Comment by Anders-Markvardsen** [comment]
In a separate issue or as part of this PR could you start to create some installation instruction please, targeting any python user, including someone new to python

**Comment by AnthonyLim23** [comment]
I will test it this morning

**Comment by AnthonyLim23** [comment]
I managed to run that but got an error:

```/usr/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.1dev1' to '0.1.dev1'
  normalized_version,
running develop
running egg_info
writing requirements to fitbenchmarking.egg-info/requires.txt
writing fitbenchmarking.egg-info/PKG-INFO
writing top-level names to fitbenchmarking.egg-info/top_level.txt
writing dependency_links to fitbenchmarking.egg-info/dependency_links.txt
reading manifest file 'fitbenchmarking.egg-info/SOURCES.txt'
writing manifest file 'fitbenchmarking.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python2.7/dist-packages/fitbenchmarking.egg-link (link to .)
fitbenchmarking 0.1.dev1 is already the active version in easy-install.pth

Installed /home/osboxes/work/fitbenchmarking
Processing dependencies for fitbenchmarking==0.1.dev1
Searching for python-docutils
Reading https://pypi.python.org/simple/python-docutils/
Couldn't find index page for 'python-docutils' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for python-docutils
error: Could not find suitable distribution for Requirement.parse('python-docutils')
```

**Comment by bb511** [comment]
@AnthonyLim23 Changed the name of the package to just docutils, could you try it now please?

**Comment by AnthonyLim23** [comment]
it seems to install 

```/usr/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.1dev1' to '0.1.dev1'
  normalized_version,
running develop
running egg_info
writing requirements to fitbenchmarking.egg-info/requires.txt
writing fitbenchmarking.egg-info/PKG-INFO
writing top-level names to fitbenchmarking.egg-info/top_level.txt
writing dependency_links to fitbenchmarking.egg-info/dependency_links.txt
reading manifest file 'fitbenchmarking.egg-info/SOURCES.txt'
writing manifest file 'fitbenchmarking.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python2.7/dist-packages/fitbenchmarking.egg-link (link to .)
fitbenchmarking 0.1.dev1 is already the active version in easy-install.pth

Installed /home/osboxes/work/fitbenchmarking
Processing dependencies for fitbenchmarking==0.1.dev1
Searching for docutils==0.12
Best match: docutils 0.12
Adding docutils 0.12 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for fitbenchmarking==0.1.dev1
```

but still gives an error

`/home/osboxes/work/fitbenchmarking/fitbenchmarking/results_output.py in <module>()
     26 
     27 import numpy as np
---> 28 from docutils.core import publish_string
     29 import post_processing as postproc
     30 import os

ImportError: No module named docutils.core
`

**Comment by bb511** [comment]
Close the mantidpython terminal and reopen it.

**Comment by AnthonyLim23** [comment]
did that

**Comment by bb511** [comment]
Is there a folder with docutils in its name at /usr/lib/python2.7/dist-packages ?

**Comment by AnthonyLim23** [comment]
there is a docutils but it does not look like a folder

**Comment by bb511** [comment]
Is it named docutils-0.12-py2.7.egg ?

**Comment by AnthonyLim23** [comment]
```
/usr/lib/python2.7/dist-packages/docutils
/usr/lib/python2.7/dist-packages/docutils-0.12.egg-info
/usr/lib/python3/dist-packages/docutils
/usr/lib/python3/dist-packages/docutils-0.12.egg-info
```

**Comment by bb511** [comment]
The package seems to be installed properly but for some reason python can't detect it. I would say maybe make sure you are running example_runScript.py with python 2.7 . Otherwise, I don't really know why this is happenning.

**Comment by AnthonyLim23** [comment]
by using mantidpython we cannot chose the python version

**Comment by bb511** [comment]
Yes, but it should be 2.7 by default, at least in the currently available version.

**Comment by AnthonyLim23** [comment]
but it may be a different installation of python

**Comment by AnthonyLim23** [comment]
still doesnt work

**Comment by bb511** [comment]
Ok, seems like python is not seeing new packages on your machine. Unfortunately, I don't really know how to fix this issue. Maybe try to restart your machine and try again?

**Comment by AnthonyLim23** [comment]
the docutils dir is empty

**Comment by bb511** [comment]
Delete the docutils folders and any additional folders in `/fitbenchmarking/` and then run `sudo python setup.py develop` in the normal terminal. Alternatively, after deleteing, run `sudo python setup.py build` and `sudo python setup.py install` .

**Comment by AnthonyLim23** [comment]
neither of those worked for me

**Comment by bb511** [comment]
I am sorry but I have no clue why you are experiencing these issues. The docutils package is detected as missing and should install but for some reason it does not without even giving an error, from what you've told me.

**Comment by AnthonyLim23** [comment]
it works if I use 

```pip install --upgrade --force-reinstall docutils```

**Comment by bb511** [comment]
The setup tools develop command uses PyPI to get its packages, just like pip. Unfortunately, there is no force-install or something similar with setup tools. At the same time, I am really confused as to why the setup tools does not manage to install the package once it finds it. This is how it should look when it actually installs the package: 
image

**Comment by AnthonyLim23** [comment]
I will have another look this afternoon. Got something to finish off first

**Comment by AnthonyLim23** [comment]
I have got it to work now. I had to use the command:

```sudo python setup.py install --force'''

Could you please add some install instructions?

**Comment by bb511** [comment]
Sorry, what command?

**Comment by bb511** [comment]
I made an issue regarding install instructions.

**Comment by AnthonyLim23** [comment]
you should put the issue in the PR. The issue is #25

**Pull request merged**
